import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const read = (relativePath) => fs.readFileSync(path.join(repoRoot, relativePath), 'utf8')

const plan = read('frontend/src/pages/Plan.jsx')
const catalog = read('frontend/src/pages/PlanCatalog.jsx')
const calendar = read('frontend/src/components/calendar/ForgedCalendar.jsx')
const dayView = read('frontend/src/components/calendar/ForgedDayView.jsx')
const raceEditor = read('frontend/src/components/calendar/RaceEditSheet.jsx')
const racesRoute = read('backend/src/routes/races.js')
const plansRoute = read('backend/src/routes/plans.js')
const runsRoute = read('backend/src/routes/runs.js')
const history = read('frontend/src/pages/History.jsx')

assert.match(plan, /api\.get\('\/races'\)/, 'Train loads the user-owned race row')
assert.match(plan, /api\.get\('\/runs'/, 'Train loads recorded activities for calendar overlays')
assert.match(plan, /calendarDateRange\(nextCalendar, todayISO\(\)\)/, 'Train bounds activity loading to the active calendar plus today')
assert.match(plan, /runDateRange[\s\S]*limit: 500/, 'the bounded calendar query can cover a full twenty-week plan')
assert.match(runsRoute, /date >= \? AND date <= \?[\s\S]*\[req\.user\.id, startDate, endDate, limit\]/, 'calendar-range run reads remain owner scoped')
assert.match(history, /api\.get\(`\/runs\/\$\{encodeURIComponent\(runId\)\}`\)/, 'History directly loads a linked run outside its default list')
assert.match(plan, /api\.patch\(`\/races\/\$\{encodeURIComponent\(activeRace\.id\)\}`/, 'race saves target the selected race id')
assert.match(racesRoute, /router\.patch\('\/:id', auth/, 'race editing remains authenticated')
assert.match(racesRoute, /SELECT \* FROM race_events WHERE id=\? AND user_id=\?/, 'race ownership is checked before editing')
assert.match(racesRoute, /UPDATE race_events[\s\S]*WHERE id=\? AND user_id=\?/, 'race mutation is owner scoped')
assert.match(racesRoute, /const identityChanged =[\s\S]*course_profile_json: null[\s\S]*SET race_name=\?, race_date=\?, distance_miles=\?[\s\S]*course_profile_json=\?/, 'identity edits clear stale course facts before a rebuild')
assert.match(plansRoute, /router\.put\('\/my\/race-link', auth[\s\S]*SELECT \* FROM race_events WHERE id=\? AND user_id=\?[\s\S]*updateActivePlanData/, 'legacy race linkage is authenticated, owner checked, and persisted through the active-plan mutation path')
assert.match(plan, /api\.put\('\/plans\/my\/race-link'[\s\S]*api\.patch\(`\/races\//, 'legacy linkage is made durable before changing the race identity')
assert.match(raceEditor, /Goal time/, 'race editor exposes the goal-time control')
assert.match(raceEditor, /race_name:[\s\S]*race_date:[\s\S]*distance_miles:[\s\S]*goal_time_seconds:/, 'race editor submits the editable race identity and goal')
assert.match(raceEditor, /race\.race_name[\s\S]*race\.race_date[\s\S]*race\.distance_miles[\s\S]*race\.goal_time_seconds[\s\S]*race\.location/, 'every race identity, course, or goal edit prompts a plan rebuild review')
assert.match(raceEditor, /fontSize: 16/, 'race form controls avoid iOS input auto-zoom')
assert.match(plan, /indexRecordedRuns\(runs\)/, 'recorded runs are indexed separately from plan sessions')
assert.match(calendar, /recordedRunsByDate\?\.get\(day\.dateISO\)/, 'week rows receive same-date recorded runs')
assert.match(calendar, /cell\.hasRecordedRun/, 'activity-only month dates remain openable')
assert.match(dayView, /Recorded separately from this plan/, 'off-plan activity is never presented as plan completion')
assert.match(plan, /navigate\(`\/history\?runId=\$\{encodeURIComponent\(activity\.id\)\}`\)/, 'recorded activity opens its existing History recap')
assert.match(catalog, /location\.state\?\.raceId[\s\S]*openRace\(race, 'owned'\)/, 'plan rebuild handoff opens the exact edited race')
assert.match(catalog, /planDialogRef[\s\S]*event\.key === 'Escape'[\s\S]*node\.inert = true[\s\S]*document\.body\.style\.overflow = 'hidden'/, 'rebuild dialog traps focus, closes with Escape, makes the background inert, and locks scrolling')
assert.match(catalog, /role="dialog"[\s\S]*aria-modal="true"[\s\S]*aria-labelledby="plan-options-title"/, 'rebuild dialog exposes modal semantics and an accessible title')

console.log('RACE CALENDAR ACTIVITY SMOKE OK (25)')
