const ACCOUNT_EXPORT_TABLES = [
  { key: 'runs', table: 'runs', orderBy: 'COALESCE(date, created_at) DESC' },
  { key: 'lifts', table: 'lifts', orderBy: 'COALESCE(date, created_at) DESC' },
  { key: 'workout_sessions', table: 'workout_sessions', orderBy: 'started_at DESC' },
  { key: 'workout_sets', table: 'workout_sets', orderBy: 'logged_at DESC' },
  { key: 'daily_checkins', table: 'daily_checkins', orderBy: 'checkin_date DESC' },
  { key: 'checkin_overrides', table: 'checkin_overrides', orderBy: 'date DESC' },
  { key: 'race_events', table: 'race_events', orderBy: 'race_date DESC' },
  { key: 'training_plans', table: 'training_plans', where: 'user_id = ?', orderBy: 'created_at DESC' },
  { key: 'user_plans', table: 'user_plans', orderBy: 'created_at DESC' },
  { key: 'personal_records', table: 'personal_records', orderBy: 'achieved_at DESC' },
  { key: 'injury_logs', table: 'injury_logs', orderBy: 'date DESC' },
  { key: 'pt_exercises', table: 'pt_exercises', orderBy: 'date DESC, created_at DESC' },
  { key: 'pt_milestones', table: 'pt_milestones', orderBy: 'date ASC, created_at ASC' },
  { key: 'journal_entries', table: 'journal_entries', orderBy: 'created_at DESC' },
  { key: 'gear_shoes', table: 'gear_shoes', orderBy: 'created_at DESC' },
  { key: 'ai_usage', table: 'ai_usage', orderBy: 'created_at DESC' },
  { key: 'suggested_goals', table: 'suggested_goals', orderBy: 'created_at DESC' },
  { key: 'milestones_seen', table: 'milestones_seen', orderBy: 'seen_at DESC' },
  { key: 'user_badges', table: 'user_badges', orderBy: 'earned_at DESC' },
  { key: 'user_challenges', table: 'user_challenges', orderBy: 'joined_at DESC' },
  { key: 'step_logs', table: 'step_logs', orderBy: 'log_date DESC' },
  { key: 'activity_feed', table: 'activity_feed', orderBy: 'created_at DESC' },
  { key: 'activity_likes', table: 'activity_likes', orderBy: 'created_at DESC' },
  { key: 'activity_comments', table: 'activity_comments', orderBy: 'created_at DESC' },
  { key: 'activity_media', table: 'activity_media', columns: 'id, activity_id, activity_type, user_id, mime_type, created_at', orderBy: 'created_at DESC' },
  { key: 'follows_as_follower', table: 'follows', where: 'follower_id = ?', orderBy: 'created_at DESC' },
  { key: 'follows_as_following', table: 'follows', where: 'following_id = ?', orderBy: 'created_at DESC' },
  { key: 'community_posts', table: 'community_posts', orderBy: 'created_at DESC' },
  { key: 'community_workouts', table: 'community_workouts', orderBy: 'created_at DESC' },
  { key: 'saved_workouts', table: 'saved_workouts', orderBy: 'created_at DESC' },
  { key: 'shared_routes', table: 'shared_routes', orderBy: 'created_at DESC' },
  { key: 'route_likes', table: 'route_likes', orderBy: 'created_at DESC' },
  { key: 'app_feedback', table: 'app_feedback', orderBy: 'created_at DESC' },
  { key: 'events', table: 'events', orderBy: 'created_at DESC' },
  { key: 'user_consents', table: 'user_consents', columns: 'id, user_id, consent_type, version, ip, created_at', orderBy: 'created_at DESC' },
  { key: 'settings', table: 'user_settings', where: "user_id = ? AND key NOT IN ('garmin_credentials')", columns: 'key, value, updated_at, created_at', orderBy: 'key ASC' },
  { key: 'watch_sync', table: 'watch_sync', orderBy: 'synced_at DESC' },
  { key: 'garmin_sleep', table: 'garmin_sleep', orderBy: 'calendar_date DESC' },
  { key: 'whoop_data', table: 'whoop_data', orderBy: 'date DESC, synced_at DESC' },
  { key: 'oura_data', table: 'oura_data', orderBy: 'date DESC, synced_at DESC' },
  { key: 'health_sync', table: 'health_sync', orderBy: 'synced_at DESC' },
  { key: 'user_hr_profile', table: 'user_hr_profile', orderBy: 'updated_at DESC' },
  { key: 'push_subscriptions', table: 'push_subscriptions', columns: 'id, user_id, endpoint, created_at', orderBy: 'created_at DESC' },
  { key: 'custom_exercises', table: 'exercises', where: 'created_by_user_id = ?', columns: 'id, name, muscle_group, secondary_muscles, instructions, how_to_image_url, is_system, created_by_user_id, approved, created_at', orderBy: 'created_at DESC' },
  { key: 'strava_connection', table: 'strava_tokens', columns: 'user_id, expires_at, athlete_id, athlete_name, connected_at', orderBy: 'connected_at DESC' },
  { key: 'whoop_connection', table: 'whoop_tokens', columns: 'user_id, whoop_user_id, display_name, connected_at, updated_at', orderBy: 'connected_at DESC' },
  { key: 'oura_connection', table: 'oura_tokens', columns: 'user_id, display_name, connected_at, updated_at', orderBy: 'connected_at DESC' },
];

const ACCOUNT_SECRET_TABLES = [
  'password_reset_tokens',
];

const ACCOUNT_DELETE_QUERIES = [
  ['DELETE FROM password_reset_tokens WHERE user_id = ?', [0]],
  ['DELETE FROM push_subscriptions WHERE user_id = ?', [0]],
  ['DELETE FROM ai_usage WHERE user_id = ?', [0]],
  ['DELETE FROM app_feedback WHERE user_id = ?', [0]],
  ['DELETE FROM events WHERE user_id = ?', [0]],
  ['DELETE FROM user_consents WHERE user_id = ?', [0]],
  ['DELETE FROM suggested_goals WHERE user_id = ?', [0]],
  ['DELETE FROM milestones_seen WHERE user_id = ?', [0]],
  ['DELETE FROM user_challenges WHERE user_id = ?', [0]],
  ['DELETE FROM step_logs WHERE user_id = ?', [0]],
  ['DELETE FROM user_badges WHERE user_id = ?', [0]],
  ['DELETE FROM route_likes WHERE user_id = ? OR route_id IN (SELECT id FROM shared_routes WHERE user_id = ?)', [0, 0]],
  ['DELETE FROM activity_likes WHERE user_id = ?', [0]],
  ['DELETE FROM activity_likes WHERE activity_id IN (SELECT id FROM runs WHERE user_id = ?)', [0]],
  ['DELETE FROM activity_likes WHERE activity_id IN (SELECT id FROM lifts WHERE user_id = ?)', [0]],
  ['DELETE FROM activity_likes WHERE activity_id IN (SELECT id FROM activity_feed WHERE user_id = ?)', [0]],
  ['DELETE FROM activity_likes WHERE activity_id IN (SELECT id FROM community_posts WHERE user_id = ?)', [0]],
  ['DELETE FROM activity_comments WHERE user_id = ?', [0]],
  ['DELETE FROM activity_comments WHERE activity_id IN (SELECT id FROM runs WHERE user_id = ?)', [0]],
  ['DELETE FROM activity_comments WHERE activity_id IN (SELECT id FROM lifts WHERE user_id = ?)', [0]],
  ['DELETE FROM activity_comments WHERE activity_id IN (SELECT id FROM activity_feed WHERE user_id = ?)', [0]],
  ['DELETE FROM activity_comments WHERE activity_id IN (SELECT id FROM community_posts WHERE user_id = ?)', [0]],
  ['DELETE FROM activity_media WHERE user_id = ?', [0]],
  ['DELETE FROM activity_media WHERE activity_id IN (SELECT id FROM runs WHERE user_id = ?)', [0]],
  ['DELETE FROM activity_media WHERE activity_id IN (SELECT id FROM lifts WHERE user_id = ?)', [0]],
  ['DELETE FROM activity_media WHERE activity_id IN (SELECT id FROM activity_feed WHERE user_id = ?)', [0]],
  ['DELETE FROM activity_media WHERE activity_id IN (SELECT id FROM community_posts WHERE user_id = ?)', [0]],
  ['DELETE FROM follows WHERE follower_id = ? OR following_id = ?', [0, 0]],
  ['DELETE FROM saved_workouts WHERE user_id = ?', [0]],
  ['DELETE FROM community_posts WHERE user_id = ?', [0]],
  ['DELETE FROM community_workouts WHERE user_id = ?', [0]],
  ['DELETE FROM activity_feed WHERE user_id = ?', [0]],
  ['DELETE FROM shared_routes WHERE user_id = ?', [0]],
  ['DELETE FROM journal_entries WHERE user_id = ?', [0]],
  ['DELETE FROM pt_exercises WHERE user_id = ?', [0]],
  ['DELETE FROM pt_milestones WHERE user_id = ?', [0]],
  ['DELETE FROM injury_logs WHERE user_id = ?', [0]],
  ['DELETE FROM workout_sets WHERE user_id = ?', [0]],
  ['DELETE FROM workout_sessions WHERE user_id = ?', [0]],
  ['DELETE FROM user_plans WHERE user_id = ?', [0]],
  ['DELETE FROM training_plans WHERE user_id = ?', [0]],
  ['DELETE FROM whoop_data WHERE user_id = ?', [0]],
  ['DELETE FROM whoop_tokens WHERE user_id = ?', [0]],
  ['DELETE FROM oura_data WHERE user_id = ?', [0]],
  ['DELETE FROM oura_tokens WHERE user_id = ?', [0]],
  ['DELETE FROM strava_tokens WHERE user_id = ?', [0]],
  ['DELETE FROM garmin_sleep WHERE user_id = ?', [0]],
  ['DELETE FROM watch_sync WHERE user_id = ?', [0]],
  ['DELETE FROM health_sync WHERE user_id = ?', [0]],
  ['DELETE FROM user_hr_profile WHERE user_id = ?', [0]],
  ['DELETE FROM lifts WHERE user_id = ?', [0]],
  ['DELETE FROM runs WHERE user_id = ?', [0]],
  ['DELETE FROM personal_records WHERE user_id = ?', [0]],
  ['DELETE FROM daily_checkins WHERE user_id = ?', [0]],
  ['DELETE FROM checkin_overrides WHERE user_id = ?', [0]],
  ['DELETE FROM race_events WHERE user_id = ?', [0]],
  ['DELETE FROM gear_shoes WHERE user_id = ?', [0]],
  ['DELETE FROM exercises WHERE created_by_user_id = ?', [0]],
  ['DELETE FROM user_settings WHERE user_id = ?', [0]],
];

function bindUserId(params, userId) {
  return params.map(() => userId);
}

function buildExportSql({ table, columns = '*', where = 'user_id = ?', orderBy }) {
  return `SELECT ${columns} FROM ${table} WHERE ${where}${orderBy ? ` ORDER BY ${orderBy}` : ''}`;
}

module.exports = {
  ACCOUNT_EXPORT_TABLES,
  ACCOUNT_SECRET_TABLES,
  ACCOUNT_DELETE_QUERIES,
  bindUserId,
  buildExportSql,
};
